langs = ['French', 'English', 'Spanish', 'Chinese', 'Japanese']
print(langs)
print(langs[2])
print(langs[-1])
langs.append('Korean')
print(langs)
langs.insert(3, 'Portuguese')
print(langs)
del langs[0]
print(langs)
print(langs.pop())
print(langs)
langs.remove('Spanish')
print(langs)
langs.sort()
print(langs)
print(sorted(langs, reverse=True))
langs.reverse()
print(langs)
